###############################################################################
# Schuberg Philis
#
# Services Onboarding
#
# Please see readme.md for details
###############################################################################
#

#
#################################################################################################

trigger:
  branches:
    include:
    - "master"

variables:
  vmImage: 'windows-2019'
  jsonPath: '$(Pipeline.Workspace)/artifact/s/services.json'
  location: 'West Europe'
  serviceGroup: 'svgr'

resources:
  repositories:
    - repository: sources
      type: git
      name: ccoe/sources
      ref: refs/heads/master

stages:
- template: Pipelines/stages/publishArtifact.yml@sources
  parameters:
    vmImage: '${{ variables.vmImage }}'

- stage: deploy_dev001
  displayName: deploy dev001
  jobs:
  - template: Pipelines/jobs/deployServices.yml@sources
    parameters:
      connectedServiceName: "${{ format('{0}-dev001-sub-spn', variables.serviceGroup) }}"
      environmentName: 'dev001'
      location: '${{ variables.location }}'
      jsonPath: '${{ variables.jsonPath }}'
      serviceGroup: '${{ variables.serviceGroup }}'
      vmImage: '${{ variables.vmImage }}'

#- stage: deploy_tst001
#  dependsOn: deploy_dev001
#  displayName: deploy tst001
#  jobs:
#  - template: Pipelines/jobs/deployServices.yml@sources
#    parameters:
#      connectedServiceName: "${{ format('{0}-tst001-sub-spn', variables.serviceGroup) }}"
#      environmentName: 'tst001'
#      location: '${{ variables.location }}'
#      jsonPath: '${{ variables.jsonPath }}'
#      serviceGroup: '${{ variables.serviceGroup }}'
#      vmImage: '${{ variables.vmImage }}'
#
#- stage: deploy_acc001
#  dependsOn: deploy_tst001
#  displayName: deploy acc001
#  jobs:
#  - template: Pipelines/jobs/deployServices.yml@sources
#    parameters:
#      connectedServiceName: "${{ format('{0}-tst001-sub-spn', variables.serviceGroup) }}"
#      environmentName: 'acc001'
#      location: '${{ variables.location }}'
#      jsonPath: '${{ variables.jsonPath }}'
#      serviceGroup: '${{ variables.serviceGroup }}'
#      vmImage: '${{ variables.vmImage }}'
#
#- stage: deploy_prd001
#  dependsOn: deploy_acc001
#  displayName: deploy prd001
#  jobs:
#  - template: Pipelines/jobs/deployServices.yml@sources
#    parameters:
#      connectedServiceName: "${{ format('{0}-tst001-sub-spn', variables.serviceGroup) }}"
#      environmentName: 'prd001'
#      location: '${{ variables.location }}'
#      jsonPath: '${{ variables.jsonPath }}'
#      serviceGroup: '${{ variables.serviceGroup }}'
#      vmImage: '${{ variables.vmImage }}'